# cspell:Disable
require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  DisabledByDefault: true
  NewCops: enable
  Exclude:
    - "app/assets/**/*"
    - "app/views/**/*.erb"
    - "lib/tasks/**/*"
    - ".vscode/**/*"
    - ".bundle/**/*"
    - ".circleci/**/*"
    - ".semaphore/**/*"
    - "**/log/**/*"
    - "**/public/**/*"
    - "**/tmp/**/*"
    - "**/templates/**/*"
    - "**/vendor/**/*"
    - "node_modules/**/*"
    - "bin/**/*"
    - "db/schema.rb"
    - "spec/factories/**/*" # Exclude factory files

# ====================================================================================================
# All access modifier related rules
# ====================================================================================================
Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Lint/UselessAccessModifier:
  Enabled: true

Style/AccessModifierDeclarations:
  Enabled: true

Layout/AccessModifierIndentation:
  Enabled: true

# ====================================================================================================
# All comment related rules
# ====================================================================================================
Layout/CommentIndentation:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
  SafeAutoCorrect: true

# ====================================================================================================
# All Class related rules
# ====================================================================================================
Layout/ClassStructure:
  Enabled: true
  ExpectedOrder:
    - module_inclusion
    - macros
    - constants
    - public_attribute_macros
    - association
    - initializer
    - public_class_methods
    - public_methods
    - protected_methods
    - private_methods

Layout/EmptyLinesAroundClassBody:
  Enabled: true

# ====================================================================================================
# All Method related rules
# ====================================================================================================
Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: leading

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Style/RedundantReturn:
  Enabled: true
  AllowMultipleReturnValues: true

Layout/SpaceBeforeFirstArg:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/FirstParameterIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstArgumentIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

# ====================================================================================================
# All Hash related rules
# ====================================================================================================
Layout/HashAlignment:
  Enabled: true
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true
  EnforcedStyle: new_line

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Style/HashSyntax:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  Enabled: true

# ====================================================================================================
# All misc whitespace related rules
# ====================================================================================================
Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundKeyword:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true
  AllowForAlignment: true

Layout/SpaceBeforeComma:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/LeadingCommentSpace:
  Enabled: true

# ====================================================================================================
# All empty lines related rules
# ====================================================================================================
Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

# ====================================================================================================
# All naming convention related rules for variables
# ====================================================================================================
Naming/MemoizedInstanceVariableName:
  Enabled: true
  EnforcedStyleForLeadingUnderscores: required

# ====================================================================================================
# All misc rules that don't fall into other categories
# ====================================================================================================
Style/AndOr:
  Enabled: true

Layout/CaseIndentation:
  Enabled: true

Layout/LineLength:
  Enabled: true
  Max: 120
  AllowedPatterns:
    - '^\s*#'
    - '^\s*"' 
    - "^\\s*'"
    - '"$'
    - "'$"
    - '\/$'

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/IndentationStyle:
  Enabled: true
  EnforcedStyle: spaces

Layout/ExtraSpacing:
  Enabled: true
  AllowForAlignment: false

Style/ParenthesesAroundCondition:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/RedundantPercentQ:
  Enabled: true

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable

Style/Semicolon:
  Enabled: true
  AllowAsExpressionSeparator: false

Lint/BooleanSymbol:
  Enabled: true

# ====================================================================================================
# All flow(if/while/for/until) statements related
# ====================================================================================================
Lint/AssignmentInCondition:
  Enabled: true
  AllowSafeAssignment: true

# ====================================================================================================
# All Bundler cop rules
# ====================================================================================================
Bundler/OrderedGems:
  Enabled: true
  TreatCommentsAsGroupSeparators: true

# ====================================================================================================
# All Rails cop rules
# ====================================================================================================
Rails:
  Enabled: false

Rails/Date:
  Enabled: true

Rails/TimeZone:
  Enabled: true
